"""add anonymous users and sessions

Revision ID: a80283ddc4c1
Revises: 3a26c1348aef
Create Date: 2026-09-18 00:11:50.849322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80283ddc4c1'
down_revision: Union[str, Sequence[str], None] = '3a26c1348aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS people")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='people'
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['people.users.id'], name='fk_sessions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='people'
    )
    op.add_column('conversations', sa.Column('user_id', sa.UUID(), nullable=False), schema='conversations')
    op.create_foreign_key('fk_conversations_user_id', 'conversations', 'users', ['user_id'], ['id'], source_schema='conversations', referent_schema='people', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_user_id', 'conversations', schema='conversations', type_='foreignkey')
    op.drop_column('conversations', 'user_id', schema='conversations')
    op.drop_table('sessions', schema='people')
    op.drop_table('users', schema='people')
    op.execute("DROP SCHEMA IF EXISTS people")
    # ### end Alembic commands ###
