"""create challenge progress table

Revision ID: f2a3a9de7654
Revises: a80283ddc4c1
Create Date: 2026-09-26 00:59:55.425997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a3a9de7654'
down_revision: Union[str, Sequence[str], None] = 'a80283ddc4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('challenge_step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['people.users.id'], name='fk_challenge_progress_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    schema='people'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_progress', schema='people')
    # ### end Alembic commands ###
